networks:
  default:
    name: xoxxox_netmid
    external: true
services:
  xoxxox_appmid:
    image: xoxxox_envmid:001
    container_name: xoxxox_appmid
    volumes:
    - ../../../export:/opt/common
    - ../../../strage:/opt/strage
    env_file:
    - ./envdir.txt
    ports:
    - 10001:80
    command: bash -c "python /opt/common/bin/xoxxox/srvmid.py --numset 4 --numget 4"
